name: Pipeline CI

on:
  push:
    branches:
    - master
    - dev
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        profile:
            - gemflux
            - starrsem
            - starflux
            - markdup
            - rmdup
            - ihec

    env:
      CI_PROFILE: ${{ matrix.profile }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run pipeline
      run: . .circ && ci test
